Create download history element #100
chainhackers/gamejutsu-demos pull request #104
Opened 2023-01-13 09:49 UTC by poludnev

2023-01-25 13:47 UTC, utgarda requested changes

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +        if (gameType === 'tic-tac-toe') {
Это точно так надо?

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +
можно и поменьше пустых строк

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +    formattedMessages.oldState.cells = formattedMessages.oldState.cells.map((cell :string) => String(cell)).join()
Что делает
```typescript
.map((cell :string) => String(cell))
```

похоже с первого взгляда, что преобразует строки в с троки?

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +          const move = JSON.stringify(defaultAbiCoder.decode(CHECKERS_MOVE_TYPES, gameMove.move));
Какой выходной формат - если это YAML, то нужно ли превращать объекты в строке в формате JSON? Не лучше ли собрать целиком большой объект, который можно отформатировать в YAML целиком?

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +    a.download = 'myfilename.txt';
myfilename ;)
hello world

Название файла лучше содержательное, например, `gj_checkers_0x123_0x456_2023.01.35.01.15.yaml`

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +          <button className={styles.submitButton} type='submit'>Get History</button>
Get history -> Download game record

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +        if (gameType === 'tic-tac-toe') {
Если запись крестиков-ноликов не предусмотрена, стоит в явной форме это обозначить - здесь добавить лог, и не показывать кнопку при игре не в шашки.

2023-01-25 13:47 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +    // console.log('history', history)
Не храни консервы в комментариях, пожалуйста.

2023-01-30 13:30 UTC, ghUserrrr commented on components/GetHistory/GetHistory.tsx
> +        if (gameType === 'tic-tac-toe') {
переделал, добавил функционал и для крестиков ноликов

2023-01-30 13:30 UTC, ghUserrrr commented on components/GetHistory/GetHistory.tsx
> +
сделано

2023-01-30 13:31 UTC, ghUserrrr commented on components/GetHistory/GetHistory.tsx
> +    formattedMessages.oldState.cells = formattedMessages.oldState.cells.map((cell :string) => String(cell)).join()
преобразует массив в строку, переделал, вынес в отдельную функцию arrayToString()

2023-01-30 13:31 UTC, ghUserrrr commented on components/GetHistory/GetHistory.tsx
> +    a.download = 'myfilename.txt';
сделано

2023-01-30 13:31 UTC, ghUserrrr commented on components/GetHistory/GetHistory.tsx
> +          <button className={styles.submitButton} type='submit'>Get History</button>
сделано

2023-01-30 13:31 UTC, ghUserrrr commented on components/GetHistory/GetHistory.tsx
> +    // console.log('history', history)
сделано

2023-01-30 15:25 UTC, utgarda approved these changes
@ghUserrrr пожалуйста, поменяй имя скачиваемого файла на строку без пробела, и добавь в описание PR пример YAML, который получается этим кодом.

2023-01-30 15:25 UTC, utgarda commented on components/GetHistory/GetHistory.tsx
> +    a.download = `game record ${formattedDate}.txt`;
Имена файлов, пожалуйста, по-старинке, без пробелов.

2023-01-30 15:36 UTC, utgarda commented
@ghUserrrr покажи готовый файл вот так
```yaml
some_list:
    - a
    - b
    - c
some_int: 1
```

2023-02-01 12:32 UTC, ghUserrrr commented
отрывок выходящего лога
{
  gameId: 731,
  gameType: checkers,
  messages:
    [
      {
          senderAddress: "0x4114b0a5ea0fD52385711639883A73F99D65dfa7",
          sent: 2023-01-30T08:31:27.133Z,
          id: d4abcf31ff8ad9c0b7af06cbaa34f93a8a06ee5ad8ebcaf8dc37109e32f649b2,
          messageType: ISignedGameMove,
          nonce: 7,
          oldState:
            {
              winner: null,
              redMoves: false,
              cells: "11111110110100000200200202222222",
              disputableMoves: []
            },
          newState:
            {
              winner: null,
              redMoves: true,
              cells: "11111110110102000000200202222222",
              disputableMoves: []
            },

2023-02-07 16:03 UTC, closed without merging