91 checkers disclaimer
chainhackers/gamejutsu-demos pull request #111
Opened 2023-01-17 08:41 UTC by ghUserrrr

2023-01-17 17:25 UTC, utgarda requested changes
Please make it mergeable - merge main into your branch. Ask @poludnev if he has done the same thing already. Pls use version above 1.1.1

2023-01-17 17:25 UTC, utgarda commented on pages/_app.tsx
> +const version = '1.1.0';
at least 1.1.2 by now :)

2023-01-18 11:45 UTC, poludnev requested changes

2023-01-18 11:45 UTC, poludnev commented on pages/games/gameType.module.scss
>  }
please fix the line end

2023-01-18 14:14 UTC, poludnev approved these changes

2023-01-18 14:17 UTC, utgarda approved these changes

2023-01-18 14:17 UTC, merged