69 wrong last move
chainhackers/gamejutsu-demos pull request #148
Opened 2023-03-04 11:24 UTC by ghUserrrr

now the cheater sees the "end the game" button
both players can end the game
cheater's screen: 

![Image](https://user-images.githubusercontent.com/109285732/222897203-97d34801-b7c6-411e-ae2f-6e2ee4423334.png)

![Image](https://user-images.githubusercontent.com/109285732/222897204-16c5e427-88b3-4f8f-ae63-db8afc22a1c0.png)

2023-03-04 12:06 UTC, utgarda requested changes
Looks good. Please take care of message wordings.

2023-03-04 12:06 UTC, utgarda commented on pages/games/[gameType].tsx
> +    let lastMove = gameState.lastOpponentMove;
Please introduce a name for this check and that helps you eliminate reassigning `lastMove`:
```typescript
const aReadableNameForThisCheckResult = lastNonce > lastOpponentNonce && gameState.lastMove !== null
const lastMove = aReadableNameForThisCheckResult ? gameState.lastOpponentMove : lastMove;
```

2023-03-06 16:12 UTC, ghUserrrr commented on pages/games/[gameType].tsx
> +    let lastMove = gameState.lastOpponentMove;
запишу 
opponentsOrOwnMoveToSend

2023-03-07 14:38 UTC, ghUserrrr commented on pages/games/[gameType].tsx
> +    let lastMove = gameState.lastOpponentMove;
done

2023-03-08 10:36 UTC, poludnev approved these changes

2023-03-08 11:28 UTC, utgarda approved these changes

2023-03-08 11:28 UTC, merged