167 header mobile layout
chainhackers/gamejutsu-demos pull request #186
Opened 2023-07-10 09:32 UTC by habdevs

2023-07-10 10:44 UTC, poludnev requested changes

2023-07-10 10:44 UTC, poludnev commented on styles/globals.css
> +@import url('https://fonts.googleapis.com/css2?family=Assistant:wght@200;300;400;500;600;700;800&family=Merriweather+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1
Split fonts import into separate imports. One font - one import.

2023-07-10 10:44 UTC, poludnev commented on components/Header/Header.module.scss
> +@mixin linear-gradient($direction, $colors...) {
Mixins make sense for "reusablitiy". If you are planing to use this mixin somewhere else in the future code, put it a single file and import. If not - additional entity is not required.

2023-07-10 10:44 UTC, poludnev commented on components/Header/Header.module.scss
> +$color2: #8C5AE3;
Name var in a semantic way. Same as for the mixins, var are considered to be reusable. What if there are other vars named "color1" in the code, will you be sure that all of them are the same?

2023-07-10 10:44 UTC, poludnev commented on components/Header/Header.module.scss
> +}
end line

2023-07-10 10:44 UTC, poludnev commented on components/Header/NavPath/NavPath.tsx
> +		if (path === "/") {
This might be a guard expression. If path === '/', no need to assign segments.

2023-07-10 10:44 UTC, poludnev commented on components/Navigation/Navigation.module.scss
> +}
.

2023-07-11 07:35 UTC, utgarda requested changes
Take care of the comments please and fix the failing build

2023-07-11 07:35 UTC, utgarda commented on public/logo/account-avatar.png
Most likely, we don't need this file.

2023-07-11 07:35 UTC, utgarda commented on public/logo/gj-logo-ninja.png
I can see the logo in a much better quality in Figma
![image](https://github.com/chainhackers/gamejutsu-demos/assets/15115/52f240d1-425a-47d0-a2b6-462fd70b7730)

2023-07-11 10:31 UTC, habdevs commented on public/logo/account-avatar.png
Until the avatar upload via rainbowKit ENS is implemented, this file serves as the default avatar image when the user does not have an avatar installed.

2023-07-12 10:50 UTC, utgarda approved these changes
Pls take care of newlines and that Todo item and merge

2023-07-12 10:50 UTC, utgarda commented on components/Header/Header.tsx
> +// TODO: ДОБАВИТЬ АВАТАРЫ ИЗ ENS
We don't have to - rainbowkit does it

2023-07-12 10:50 UTC, utgarda commented on components/Navigation/Navigation.module.scss
> +}
.

2023-07-12 10:50 UTC, utgarda commented on styles/colors.scss
> +$neon-blue: #5f5afa;
.

2023-07-12 10:50 UTC, utgarda commented on styles/mixins.scss
> +}
.

2023-07-12 11:07 UTC, poludnev approved these changes

2023-07-12 11:07 UTC, poludnev commented on components/Header/Header.tsx
> +						)
.

2023-07-12 11:07 UTC, poludnev commented on components/Logo/Logo.module.scss
> +}
.

2023-07-12 11:07 UTC, poludnev commented on components/Logo/Logo.tsx
> +}
.

2023-07-12 11:07 UTC, poludnev commented on components/Navigation/Navigation.tsx
> +					{/* <li
.

2023-07-12 11:07 UTC, poludnev commented on components/Navigation/Navigation.tsx
> +}
.

2023-07-12 11:07 UTC, poludnev commented on styles/colors.css
> +	--white: #fff;
.

2023-07-12 12:11 UTC, merged